name: 'formula1'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  formula1:
    # Configuración para staging (silver)
    staging:
      bronze:  # Solo para modelos que referencian directamente a bronze
        +materialized: ephemeral  # No se materializan, solo referencias
        +database: ALUMNO3_DEV_BRONZE_DB_F1
        +schema: FORMULA_DB
      
      silver:
        +materialized: table
        +database: ALUMNO3_DEV_SILVER_DB_F1
        +schema: silver
        +persist_docs:
          relation: true
          columns: true

    # Configuración para marts (gold)    
    marts:
      +materialized: table
      +database: ALUMNO3_DEV_GOLD_DB_F1
      +schema: gold
      +persist_docs:
        relation: true
        columns: true

vars:
  # Variables globales para nombres de bases de datos
  bronze_database: 'ALUMNO3_DEV_BRONZE_DB_F1'
  silver_database: 'ALUMNO3_DEV_SILVER_DB_F1'
  gold_database: 'ALUMNO3_DEV_GOLD_DB_F1'
